### ISSUE TITLE
Can not add border style for row

### ISSUE THREAD

**Issue by NguyenNgocPhuGA** [axlsx-styler-gem/axlsx_styler#26]
I try to add style border for row but I away get  the error: undefined method `row' for nil:NilClass
![screen shot 2018-08-03 at 14 56 17](https://user-images.githubusercontent.com/37870526/43631454-71291a9c-972d-11e8-86f1-1aa1c720ee84.png)

This is my xlsx file when not add style.
<img width="709" alt="screen shot 2018-08-03 at 15 00 52" src="https://user-images.githubusercontent.com/37870526/43631684-1abccd2e-972e-11e8-9abd-a57e6a7cb07e.png">

please tech me where I wrong, or can I must config somewhere ?
Thanks :)

**Comment by zenzei** [comment]
Hello @NguyenNgocPhuGA, i'm having the same issue, how did you resolve it? Thanks

**Comment by NguyenNgocPhuGA** [comment]
@zenzei because your cell doesn't have data. You just add blank string `''` to your cell, it will be resolve.
