### ISSUE TITLE
Error when using dxf style with other styles

### ISSUE THREAD

**Issue by owst** [axlsx-styler-gem/axlsx_styler#29]
I get an error with the following reproduction:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'caxlsx', "= 3.0.1"
  gem 'axlsx_styler', "= 1.0.0"
end

# Monkey-patch a "fix" by uncommenting the line below and commenting the line
# that follows it
module AxlsxStyler
  module Styles
    def add_style(*args)
      style = args.first

      self.style_index ||= {}

      raw_style = {type: :xf, name: 'Arial', sz: 11, family: 1}.merge(style)
      if raw_style[:format_code]
        raw_style.delete(:num_fmt)
      end

      index = style_index.key(raw_style)
      if !index
        index = super
        # self.style_index[index] = raw_style unless raw_style[:type] == :dxf
        self.style_index[index] = raw_style
      end
      return index
    end
  end
end

Axlsx::Package.new do |p|
  %w[first second].each do |sheet_name|
    p.workbook.add_worksheet(name: sheet_name) do |sheet|
      sheet.add_row (1..2).to_a

      sheet.add_style "A1:A1", { bg_color: "AA0000" }
      sheet.add_style "B1:B1", { bg_color: "CC0000" }

      sheet.add_row (1..2).to_a

      highlight = p.workbook.styles.add_style(bg_color: "0000FF", type: :dxf)

      sheet.add_conditional_formatting(
        "A2:B2",
        {
          type: :cellIs,
          operator: :greaterThan,
          formula: "1",
          dxfId: highlight,
          priority: 1
        }
      )

      sheet.add_row (1..2).to_a

      sheet.add_style "A3:B3", { bg_color: "00FF00" }
    end
  end

  p.serialize('simple.xlsx')
end
```
Running this file gives:
```
Traceback (most recent call last):
	9: from bug.rb:33:in `<main>'
	8: from bug.rb:33:in `new'
	7: from /Users/owen/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.1/lib/axlsx/package.rb:29:in `initialize'
	6: from bug.rb:62:in `block in <main>'
	5: from /Users/owen/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/axlsx_styler-1.0.0/lib/axlsx_styler/axlsx_package.rb:5:in `serialize'
	4: from /Users/owen/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/axlsx_styler-1.0.0/lib/axlsx_styler/axlsx_workbook.rb:21:in `apply_styles'
	3: from /Users/owen/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each'
	2: from /Users/owen/.rbenv/versions/2.6.6/lib/ruby/2.6.0/set.rb:338:in `each_key'
	1: from /Users/owen/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/axlsx_styler-1.0.0/lib/axlsx_styler/axlsx_workbook.rb:29:in `block in apply_styles'
/Users/owen/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/caxlsx-3.0.1/lib/axlsx/workbook/worksheet/cell.rb:296:in `style=': Invalid cellXfs id (ArgumentError)
```

I tracked a "fix" down by adding the commented line in the code, I'm not quite sure I follow what's going on, but hopefully this is helpful

**Comment by westonganger** [comment]
Sorry I see this earlier. Thanks for tracking down the fix. I have now added similar code to master @ 71e7d09 Could you please test and confirm all is well?

**Comment by owst** [comment]
Hi @westonganger thanks for fixing - it seems to work with my reproduction above (using `gem 'axlsx_styler', git: "https://github.com/axlsx-styler-gem/axlsx_styler", ref: "45263e9b7a6c153fca20a958e2c69ea4dd68feaa"` in the inline Gemfile)

Would it be wise to add a regression test to ensure `dxf` styles continue to work in the future?

**Comment by westonganger** [comment]
Hold on a second here. I dont think that your DXF style is even be working in this example. Can you confirm you are seeing the correct dynamic styling with master or your fix?

**Comment by westonganger** [comment]
Given this bit of code:

https://github.com/randym/axlsx/blob/master/lib/axlsx/stylesheet/styles.rb#L234-L241

Which is called from: 

https://github.com/axlsx-styler-gem/axlsx_styler/blob/v1.0.0/lib/axlsx_styler/axlsx_styles.rb#L27

We may have seperate `style_index` caches for xf and dxf styles.

**Comment by owst** [comment]
Apologies @westonganger I only re-ran my reproduction based on master, taking no exception as it had worked! 🤦 

Indeed on master, the dxf style does not work (cell B2 does _not_ have a blue background):

<img width="99" alt="Screenshot 2020-08-25 at 17 48 50" src="https://user-images.githubusercontent.com/117234/91203816-42cafb00-e6fb-11ea-85b3-550a61c3d261.png">

With my "fix"/reproduction B2 does have a blue background as expected:

<img width="106" alt="Screenshot 2020-08-25 at 17 48 44" src="https://user-images.githubusercontent.com/117234/91203840-46f71880-e6fb-11ea-99fe-9f9c5ceb6d37.png">

I'm afraid I'm not sure if my "fix" was accidentally working or maybe hiding another problem.

**Comment by westonganger** [comment]
Your implementation was correct. However I located an additional improvement in being able to cache/reuse dxf styles. I am working on it now.

**Comment by westonganger** [comment]
Ok this is all fixed up in master now and ive added the regression test. Your implementation was basically correct. We do not need to cache dxf styles because the developer actually does this via the code.

**Comment by owst** [comment]
Hi @westonganger,

Thanks for following up - unfortunately, I don't think the fix (or test) are working - using the latest master commit in my reproduction (removing the monkey patch and using `gem 'axlsx_styler', git: 'https://github.com/axlsx-styler-gem/axlsx_styler', ref: '27e4a950f2885c1ceb21654cba4eb3b54491e440'`) I don't get an error but cell B2 still doesn't have a blue background, as it should.

Running the tests locally, the generated `test_dxf_cell.xlsx` also doesn't have a blue background in cell B2 as it looks like it should.

**Comment by westonganger** [comment]
Sorry my coding session was super scattered yesterday. I missed something when writing I have now fixed this and confirmed the test output.

**Comment by owst** [comment]
Great, thanks @westonganger 👍 - I can confirm it works as expected on master with 663f6ce53a76b42b0a28188a1e7cc817b8f938bc

**Comment by westonganger** [comment]
v1.1.0 is now released with these changes.
