### ISSUE TITLE
is it possible to add inner border for cell area?

### ISSUE THREAD

**Issue by buncis** [axlsx-styler-gem/axlsx_styler#32]
I mean when I use 

`add_border "b2:F20" `

its only give border to the sides/outer but inner like this 

![image](https://user-images.githubusercontent.com/14258779/130814305-8e17273b-9d68-403e-8418-b5c30b724d57.png)

what I want is a config/how to get this 

![image](https://user-images.githubusercontent.com/14258779/130814489-7c35d168-c49d-497d-8c4d-b60cae16bd4a.png)

**Comment by westonganger** [comment]
Use add_style "B2:F20", border: {style: :thin, color: "000000", edges: [:top, :bottom, :left, :right]}

**Comment by westonganger** [comment]
add_border is a special method to just border the outside. add_style method applies styles to all cells withhin the range
