### ISSUE TITLE
Doesnt work well with custom default font

### ISSUE THREAD

**Issue by westonganger** [axlsx-styler-gem/axlsx_styler#34]
Original Thread: https://github.com/axlsx-styler-gem/axlsx_styler/issues/14#issuecomment-1255003388

### Problem

If a user defines this in the spreadsheet it will set the default font name

```ruby
sheet.styles.fonts[0].name = 'Pontiac'
```

Currently alxsx_styler is not aware of this type of customization and assumes the following based on prior manual testing.

https://github.com/axlsx-styler-gem/axlsx_styler/blob/35795f5ecfd130c6f949035e4381c93bc29aa9ec/lib/axlsx_styler/axlsx_styles.rb#L11-L15

Seems that we can likely just change `Arial` to `sheet.styles.fonts[0].name `

Can we also make any similar dynamic improvements to `sz: 11` and/or `family: 1` ?

**Comment by westonganger** [comment]
Here are the defaults in caxlsx 

https://github.com/caxlsx/caxlsx/blob/9b6a78f43b9415bd155bddf6a6d872f5d5555595/lib/axlsx/stylesheet/styles.rb#L459

**Comment by westonganger** [comment]
This is now fixed in master via #35 

@newfylox can you test out with master and verify that it works for your use cases.

**Comment by newfylox** [comment]
I updated the old issue here https://github.com/axlsx-styler-gem/axlsx_styler/issues/14#issuecomment-1256271657

Maybe you want me to continue here?

**Comment by westonganger** [comment]
We are not sure that this is valid, this needs to have tests for this, started to look into this in #40
